version: "3.8"

services:
  postgres:
    container_name: postgres-test
    image: postgres-test
    build:
      dockerfile: ./Dockerfile-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres